# Generated by Django 4.2.12 on 2024-08-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('price', models.FloatField()),
                ('brand', models.CharField(max_length=20, null=True)),
                ('category', models.CharField(choices=[('Computer', 'Computer'), ('Screen', 'Screen'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Printer', 'Printer')], max_length=20)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
