# Generated by Django 4.2.12 on 2024-09-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='levelAccess',
        ),
    ]
